import { NextResponse } from "next/server"
import { User } from "@/models"
import bcrypt from "bcryptjs"
import { randomUUID } from "crypto" // Import UUID generator

export async function POST(request: Request) {
  try {
    const { name, username, email, password } = await request.json()

    // Validation des données
    if (!name || !username || !email || !password) {
      return NextResponse.json({ error: "Tous les champs sont requis" }, { status: 400 })
    }

    if (password.length < 6) {
      return NextResponse.json({ error: "Le mot de passe doit contenir au moins 6 caractères" }, { status: 400 })
    }

    if (username.length < 3) {
      return NextResponse.json({ error: "Le pseudo doit contenir au moins 3 caractères" }, { status: 400 })
    }

    // Vérifier si l'email existe déjà
    const existingEmail = await User.findOne({
      where: { email },
    })

    if (existingEmail) {
      return NextResponse.json({ error: "Un compte avec cet email existe déjà" }, { status: 400 })
    }

    // Vérifier si le pseudo existe déjà
    const existingUsername = await User.findOne({
      where: { username },
    })

    if (existingUsername) {
      return NextResponse.json({ error: "Ce pseudo est déjà pris" }, { status: 400 })
    }

    // Hacher le mot de passe
    const hashedPassword = await bcrypt.hash(password, 12)

    // Créer l'utilisateur
    const user = await User.create({
      id: randomUUID(), // Generate ID manually for Sequelize if not auto-generated by DB default
      name,
      username,
      email,
      password: hashedPassword,
    })

    // Retourner les données utilisateur (sans le mot de passe)
    const userJson = user.toJSON() as any
    const { password: _, ...userWithoutPassword } = userJson

    return NextResponse.json({
      message: "Compte créé avec succès",
      user: userWithoutPassword,
    })
  } catch (error) {
    console.error("Erreur lors de l'inscription:", error)
    return NextResponse.json({ error: "Erreur interne du serveur" }, { status: 500 })
  }
}